/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SeminarKitRouteImport } from './routes/seminar-kit'
import { Route as MerchandiseRouteImport } from './routes/merchandise'
import { Route as MediaPromosiRouteImport } from './routes/media-promosi'
import { Route as DocumentPrintingRouteImport } from './routes/document-printing'
import { Route as IndexRouteImport } from './routes/index'

const SeminarKitRoute = SeminarKitRouteImport.update({
  id: '/seminar-kit',
  path: '/seminar-kit',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchandiseRoute = MerchandiseRouteImport.update({
  id: '/merchandise',
  path: '/merchandise',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaPromosiRoute = MediaPromosiRouteImport.update({
  id: '/media-promosi',
  path: '/media-promosi',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentPrintingRoute = DocumentPrintingRouteImport.update({
  id: '/document-printing',
  path: '/document-printing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/document-printing': typeof DocumentPrintingRoute
  '/media-promosi': typeof MediaPromosiRoute
  '/merchandise': typeof MerchandiseRoute
  '/seminar-kit': typeof SeminarKitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/document-printing': typeof DocumentPrintingRoute
  '/media-promosi': typeof MediaPromosiRoute
  '/merchandise': typeof MerchandiseRoute
  '/seminar-kit': typeof SeminarKitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/document-printing': typeof DocumentPrintingRoute
  '/media-promosi': typeof MediaPromosiRoute
  '/merchandise': typeof MerchandiseRoute
  '/seminar-kit': typeof SeminarKitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/document-printing'
    | '/media-promosi'
    | '/merchandise'
    | '/seminar-kit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/document-printing'
    | '/media-promosi'
    | '/merchandise'
    | '/seminar-kit'
  id:
    | '__root__'
    | '/'
    | '/document-printing'
    | '/media-promosi'
    | '/merchandise'
    | '/seminar-kit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocumentPrintingRoute: typeof DocumentPrintingRoute
  MediaPromosiRoute: typeof MediaPromosiRoute
  MerchandiseRoute: typeof MerchandiseRoute
  SeminarKitRoute: typeof SeminarKitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/seminar-kit': {
      id: '/seminar-kit'
      path: '/seminar-kit'
      fullPath: '/seminar-kit'
      preLoaderRoute: typeof SeminarKitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchandise': {
      id: '/merchandise'
      path: '/merchandise'
      fullPath: '/merchandise'
      preLoaderRoute: typeof MerchandiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media-promosi': {
      id: '/media-promosi'
      path: '/media-promosi'
      fullPath: '/media-promosi'
      preLoaderRoute: typeof MediaPromosiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/document-printing': {
      id: '/document-printing'
      path: '/document-printing'
      fullPath: '/document-printing'
      preLoaderRoute: typeof DocumentPrintingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocumentPrintingRoute: DocumentPrintingRoute,
  MediaPromosiRoute: MediaPromosiRoute,
  MerchandiseRoute: MerchandiseRoute,
  SeminarKitRoute: SeminarKitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
